// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe32Zay4vZT8LLgrW8o8E0CnsFCT9vIk4',
    appId: '1:797959552222:web:68eaa873f869dc7075564f',
    messagingSenderId: '797959552222',
    projectId: 'grandmaster-6c88c',
    authDomain: 'grandmaster-6c88c.firebaseapp.com',
    storageBucket: 'grandmaster-6c88c.appspot.com',
    measurementId: 'G-YNGBJKKZ9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ15F33Kwtn64ERIUJLgMJZ_2p2K5I-rs',
    appId: '1:797959552222:android:79f17ed62dac33a275564f',
    messagingSenderId: '797959552222',
    projectId: 'grandmaster-6c88c',
    storageBucket: 'grandmaster-6c88c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlcc_i9FIgsVVyz-Dnx7XYt9-JdRL65As',
    appId: '1:797959552222:ios:78ce33e4ad8461ce75564f',
    messagingSenderId: '797959552222',
    projectId: 'grandmaster-6c88c',
    storageBucket: 'grandmaster-6c88c.appspot.com',
    iosClientId: '797959552222-akohuhargljf6v2qechh03pf87bhqqrv.apps.googleusercontent.com',
    iosBundleId: 'com.grandmaster.grandmaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlcc_i9FIgsVVyz-Dnx7XYt9-JdRL65As',
    appId: '1:797959552222:ios:78ce33e4ad8461ce75564f',
    messagingSenderId: '797959552222',
    projectId: 'grandmaster-6c88c',
    storageBucket: 'grandmaster-6c88c.appspot.com',
    iosClientId: '797959552222-akohuhargljf6v2qechh03pf87bhqqrv.apps.googleusercontent.com',
    iosBundleId: 'com.grandmaster.grandmaster',
  );
}
